[context.production.environment]
# BUG: https://github.com/nuxt/image/issues/1353
NUXT_IMAGE_PROVIDER = "ipx"
# FIXME: https://answers.netlify.com/t/corepack-and-pnpm-10-2-0-failing-on-build/138964
COREPACK_INTEGRITY_KEYS = "0"

[build]
  command = "pnpm install && pnpm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--shamefully-hoist"
  NPM_FLAGS = "--version"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
